### ISSUE TITLE
Can I get the code of video similarity visualization？

### ISSUE THREAD

**Issue by mengnan12** [MKLab-ITI/visil#13]
In my recent work，I need the visualization of video similarity，but I find there are no code of video similarity visualization，if you can provide this code，I will be very grateful!
Here is my e-mail：916370247@qq.com

**Comment by gkordo** [comment]
Hi @mengnan12. I have created a [Colab notebook](https://colab.research.google.com/drive/1XwkQpXrpyr7jjq3xCL7anASBjNfNCnkn) for this purpose. Feel free to use and modify it as you please.
