### ISSUE TITLE
Image URLs in query and database file

### ISSUE THREAD

**Issue by aastha19** [MKLab-ITI/visil#2]
I wanted to ask if we can pass image URLs in queries and database files.

**Comment by gkordo** [comment]
Unfortunately, this repo supports only video inputs, so it will not work if you provide image URLs.

**Comment by aastha19** [comment]
@gkordo  Can we pass video URLs as inputs?

**Comment by gkordo** [comment]
If the URLs are links to the source video files (e.g. the .mp4 files), then you can provide them as input. Otherwise, If the URLs are (e.g.) Youtube URLs, then you have to download the videos first, and then provide the paths to video files as input.

**Comment by aastha19** [comment]
Thanks a lot for all your help

**Comment by gkordo** [comment]
No prob!

**Comment by aastha19** [comment]
@gkordo 
Giving direct video links (eg: [link](https:\/\/r3---sn-aigl6ney.googlevideo.com\/videoplayback?expire=1574767479&ei=F7fcXeSrG9Pn1ga1jo-4Bg&ip=185.27.134.50&id=o-AEEA6-iOECaYnv6Fw39i6uijRPB1JEGUy4Su8vXGRxzw&itag=18&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-aigl6ney%2Csn-aigzrn7s&ms=au%2Crdu&mv=u&mvi=2&pl=23&mime=video%2Fmp4&gir=yes&clen=2363900&ratebypass=yes&dur=56.052&lmt=1391288539603314&mt=1574745712&fvip=3&fexp=23842630&c=WEB&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=ALgxI2wwRAIgC3YEWiAYHdLG5pursHgdqkxB3trmBuA1npEfOYe97JoCIEcFY7pDW6wrlg_p30czaw5u58ntLKYrB28DCYJPTkSy&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl&lsig=AHylml4wRgIhALdAtzShtsvl_Ibue2XVrylZiiwyQoyYJ477_03P6ktIAiEA1TCCGZaqWvrC9WC4HiwlEvznVfQeHhcNdolzBlPfasQ%3D)) result in the following error:

![image](https://user-images.githubusercontent.com/14852345/69601932-d328c200-103b-11ea-9c6c-3d322d1f2cc1.png)

This error is coming up even for the local path of mp4 videos. 
The code was run by me yesterday for the same set of videos; but today the error of "ValueError: need at least one array to concatenate" is thrown.
Any suggestion?

**Comment by gkordo** [comment]
Make sure that the provided videos exist. I assume that the error is thrown because the videos was not successfully loaded.

**Comment by aastha19** [comment]
Ok. Thanks a lot for your help
