### ISSUE TITLE
Make visil work with Python 2.7

### ISSUE THREAD

**Issue by utzcoz** [MKLab-ITI/visil#21]
I know Python 2.7 is very old and not been supported anymore, but there are some legacy infrastructures that still use Python 2.7. It's great if visil can work with Python 2.7. With local experiment, visil only needs a small change at https://github.com/MKLab-ITI/visil/blob/master/datasets/__init__.py#L11:

```
ratio = desired_size * 1.0 / min_size
``` 

In Python 2.7, the `ratio` will be 0 when `desired_size` is less than `min_size`.

**Comment by gkordo** [comment]
Thnx for the suggestion and solution.
I integrated it into the code in 8f133a884c5b2ced11267d2ce08812a8cb9a1a20.
