### ISSUE TITLE
Links not working

### ISSUE THREAD

**Issue by divyagupta25** [MKLab-ITI/visil#24]
Hi, 

Thanks for sharing your work. All the ndd.iti.gr links are not working for me. Could you please share an alternative, if any?

**Comment by gkordo** [comment]
hi @divyagupta25, you can find the model weights in the following links:
TF -> https://drive.google.com/file/d/1kHe-PKGRX9IJYtSIs1Ot_D0Zj67U1CjG/view?usp=sharing
PT -> https://drive.google.com/file/d/1_PymekVfKf1pTlTG-7j3uLwTRv_94XzJ/view?usp=sharing

**Comment by why-q** [comment]
What about "http://ndd.iti.gr/visil/pca_resnet50_vcdb_1M.pth"?
