### ISSUE TITLE
Is training triplet dataset available?

### ISSUE THREAD

**Issue by EthanGreen75** [MKLab-ITI/visil#3]
Thanks for the greak work.
     Having been intersted in your work for a long period. For this project, I want to implement the training procedure of the net but Lacking of the training data.
     It's very hard to download the full VCDB dataset(including the distractor data). Can the training VCDB triplets features public avalible ? Just as the DML features.
     Thanks a lot.

**Comment by gkordo** [comment]
Thanks for your interest, and sorry for the late response.
Unfortunately, the extracted features require a lot of storage space, so we can not provide them. However, you can download from [here](http://ndd.iti.gr/visil/triplets.pk) the triplet pools used for the training of ViSiL (cf. Section 4.5 in the [paper](http://openaccess.thecvf.com/content_ICCV_2019/papers/Kordopatis-Zilos_ViSiL_Fine-Grained_Spatio-Temporal_Video_Similarity_Learning_ICCV_2019_paper.pdf)). It is a pickle file that contains a dictionary with the following key-value pairs: 
1. 'pool1' - a list whose entries are dictionaries that contains the positive pairs and their hard negatives
2. 'pool2' - a list whose entries are dictionaries that contains single videos and their hard negatives
3. 'index' - a dictionary that maps the indexes to the VCDB video ids.

If you have any trouble going through the file, please let me know.

**Comment by tobymu** [comment]
@gkordo Hi, the download link seems not available? And when will you release the training code?

**Comment by gkordo** [comment]
If you are still interested in the training code of ViSiL, please contact us via an academic email to send you a prototype version.
