### ISSUE TITLE
Which tensorflow version works for this repo's code

### ISSUE THREAD

**Issue by ayamero** [MKLab-ITI/visil#4]
We tried tf 2.0 and tf 1.5, and each of them has some 'modules' been deprecated. Could you please tell me which tensorflow version works for visil's code? 
THX

**Comment by gkordo** [comment]
The code runs with any Tensorflow 1.xx version (tested with 1.8-1.15). I have updated the README.md to be clear.
The deprecated modules are not an issue; hence, you can ignore the warnings.

**Comment by ayamero** [comment]
We also found a small bug:

When there is only one video query in `queries.txt`/`database.txt`, in the `VideoGenerator.__init__()` process, `self.videos` will be a one dimension list, which will cause `__getitem__` fails. 

Could you please consider this situation and fix it.

**Comment by gkordo** [comment]
Thanks for the bug report. I have updated the code and the bug is fixed.
