### ISSUE TITLE
Some special cases when video is loaded

### ISSUE THREAD

**Issue by Jo-won** [MKLab-ITI/visil#6]
Some video links were not valid in the FIVR-5k data set, and I was looking for invalid videos other than them.

Then I found that the number of videos that were successfully downloaded and evaluated using the proposed evaluation code was not the same.  (4055-were successfully downloaded, 4035-evaluated)

While trying to determine the cause of this, in the data loader, i confirmed  that the first frame of some video was read from the second iteration rather than from the first iteration, in which case the algorithm in the code excluded it from the evaluation.

In this case, I would like to ask you whether i should evaluate it without special cases like the algorithm of the current code or by modifying the code to include special cases.

### Explanation of special cases

(code path : datasets/__init__.py - line 23 func. load_video)
In the algorithm of the code, when first read is False, got break.
Here special cases below (column 0: iteration index, column 1: Variable 'ret' stored readable or not)
![image](https://user-images.githubusercontent.com/46413594/96366738-8fbfd080-1184-11eb-8682-15622b12290d.png)

- founded special cases
'-Ki5scTNsM8', '7ubQk6s0gds', 'KOR2k4Lbi1g', 'LnJrmfspG6E',  'NMdbiiBL0S0', 'SJpw26YkYPI', 'VpCqnbbGHMs', 'YBuSs6mqSxQ',  '_ZcwSR90UHo', 'aWot7k6l6-M', 'c_1Eojr-B8k', 'eCmo_uembsA',  'jGK2ycDokqM', 'lgazc8OIjm0', 'oXW3WVeMC64', 'pLtZlhLzu_o', 'q8isIjpmXLE', 'v1ug2TIxLfc', 'w3cex3V64IM', 'wMYU9aXVfLs'

**Comment by Jo-won** [comment]
+) I found another special case, "YBuSs6mqSxQ"
![image](https://user-images.githubusercontent.com/46413594/96394311-98ec8400-11fc-11eb-9fc9-787e2138fc8b.png)

**Comment by gkordo** [comment]
There should be an issue with the particular video files. They might be corrupted. Could you please try to re-download the videos that are not loaded and try again?

Also, for video loading, the `ret` variable is not used as I found it to have several issues. Instead, every loaded frame is asserted to be of type `np.ndarray`.
