### ISSUE TITLE
 F tensorflow/stream_executor/cuda/cuda_dnn.cc:516] Check failed: cudnnSetTensorNdDescriptor(handle_.get(), elem_type, nd, dims.data(), strides.data()) == CUDNN_STATUS_SUCCESS (3 vs. 0)batch_descriptor: {count: 1 feature_map_count: 32 spatial: 0 86  value_min: 0.000000 value_max: 0.000000 layout: BatchDepthYX}

### ISSUE THREAD

**Issue by maliho0803** [MKLab-ITI/visil#7]
F tensorflow/stream_executor/cuda/cuda_dnn.cc:516] Check failed: cudnnSetTensorNdDescriptor(handle_.get(), elem_type, nd, dims.data(), strides.data()) == CUDNN_STATUS_SUCCESS (3 vs. 0)batch_descriptor: {count: 1 feature_map_count: 32 spatial: 0 86  value_min: 0.000000 value_max: 0.000000 layout: BatchDepthYX}

**Comment by gkordo** [comment]
This seems to be a cuDNN issue. Could you please elaborate more? When do you encounter this error?
