### ISSUE TITLE
Did you really use R-MAC on intermediate layers? 

### ISSUE THREAD

**Issue by wjtan99** [MKLab-ITI/visil#8]
In your paper at the beginning of Section 4.1, it says R-MAC is used on intermediate convolutional layers.  I found the region pooling in your code, but could not find the R-MAC in your code. Did you really use it in your final implementation? 
Thanks.

**Comment by tomatowithpotato** [comment]
region pooling == R-MAC？
I guess

**Comment by gkordo** [comment]
We have pre-calculated the kernel sizes for the input image size for each intermediate layer, and we thus use a max-pooling layer providing similar results. In that way, the feature extraction process is significantly faster.
